name: Build Android

on: [push]

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app/
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 21
          cache: npm
          cache-dependency-path: app/package-lock.json

      - name: Install app dependencies
        run: npm ci

      - name: Install Ionic CLI
        run: npm install -g @ionic/cli

      - name: Ionic version
        run: ionic version

      - name: Build Ionic App
        run: ionic build

      - name: Add Android to Capacitor
        run: npx cap add android

      - name: Sync Android
        run: npx cap sync android

#      - name: Build Android Dev APK
#        run: npx cap build android

      - name: Gradle Bundle
        run: cd android && ./gradlew bundle

      - name: Gradle Debug
        run: cd android && ./gradlew assembleDebug

      - name: Check folder content of android release
        run: ls ./android/app/build/outputs/bundle/release

      - name: Check folder content of android apk
        run: ls -R ./android/app/build/outputs/apk

#      - name: Build Android Release APK
#        run: ionic capacitor build android --release --prod
#
#      - name: Generate the Android App Bundle
#        working-directory: ./android/
#        run: ./gradlew bundle
#
#      - name: Upload dev APK
#        uses: actions/upload-artifact@v1
#        with:
#          name: app-dev
#          path: apk/app-debug.apk
#
#      - name: Upload release bundle
#        uses: actions/upload-artifact@v1
#        with:
#          name: app-release
#          path: apk/app.aab