on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: Release

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      releases_created: ${{ steps.release.outputs.releases_created }}
    steps:
      # Update the release branch version and changelog, or create a GitHub release if merged
      - uses: google-github-actions/release-please-action@v4
        id: release

  build-android:
    needs: [ release ]
    if: ${{ needs.release.outputs.releases_created }}
    uses: ./.github/workflows/android.yml
    with:
      tag: ${{ steps.release.outputs.tag_name }}
